// Code generated by "stringer -type=Language"; DO NOT EDIT

package gopicotts

import "fmt"

const _Language_name = "LanguageEnUSLanguageEnGBLanguageDeLanguageEsLanguageFrLanguageIt"

var _Language_index = [...]uint8{0, 12, 24, 34, 44, 54, 64}

func (i Language) String() string {
	if i >= Language(len(_Language_index)-1) {
		return fmt.Sprintf("Language(%d)", i)
	}
	return _Language_name[_Language_index[i]:_Language_index[i+1]]
}
